OPENAI_API_KEY ="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"
NEWS_API_KEY = "731550980011494f803777c12421a27a"
